# Generated by Django 4.0.3 on 2022-03-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto_images/%Y/%m')),
                ('slug', models.SlugField(unique=True)),
                ('preco_original', models.FloatField(default=0)),
                ('preco_promo', models.FloatField()),
                ('tam', models.CharField(choices=[('P', 'pequena'), ('M', 'média'), ('G', 'grande')], max_length=255)),
            ],
        ),
    ]
